name: Deploy to dcetl

on:
  push:
    branches: ["gh-pages"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DCETL_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Add it to known_hosts
        run: ssh-keyscan -H ${{ secrets.DCETL_HOST }} >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            gh-pages
            index.html
      - name: Deploy via rsync
        run: pwd && ls -la && rsync -avz --recursive --files-from=./.github/workflows/deploy_dcetl.lst ${{ secrets.DCETL_USER }}@${{ secrets.DCETL_HOST }}:${{ secrets.DCETL_PATH }}
