name: Deploy to dcetl

on:
  push:
    branches: ["gh-pages"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DCETL_HOST }}
          username: ${{ secrets.DCETL_USER }}
          key: ${{ secrets.DCETL_PRIVATE_KEY }}
          port: ${{ secrets.DCETL_PORT }}
          source: "index.html,gh-pages"
          target: ${{ secrets.DCETL_PATH }}
